apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bwcafish.fullname" . }}
  labels:
    {{- include "bwcafish.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "bwcafish.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bwcafish.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: VERSION
              value: "{{ .Values.image.tag }}"
          {{- if .Values.telemetry.enabled }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "{{ .Values.telemetry.otelCollectorUrl }}"
            - name: OTEL_EXPORTER_OTLP_APIKEY
              value: "{{ .Values.telemetry.otelApiKey }}"
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

